### ISSUE TITLE
How can I get only one NPM package published as private?

### ISSUE THREAD

**Issue by mksglu** [dropseed/deps-js#34]
Hello there. I have an NPM package released as private. I only want PR when this package is upgraded. Is there a setting for this? Thx.

**Comment by davegaeddert** [comment]
Hey @mksglu, you should be able to use update `filters` for this. Something along these lines in your deps.yml:

```yaml
version: 3
dependencies:
- type: js
  lockfile_updates:
    enabled: false
  manifest_updates:
    # Filters are evaluated *in order*
    # so each dependency will use the first rule that it matches
    filters:
    - name: ".*"
      enabled: false
    - name: my-private-package
      enabled: true
```

https://www.dependencies.io/config/#disabling-updates-for-a-direct-dependency

Does that sound like what you're looking for?
